### ISSUE TITLE
MegaDepth train images for Florence Cathedral

### ISSUE THREAD

**Issue by actruce** [monniert/dti-clustering#3]
Hi! I am wondering if you can provide the directory name (number) for Florence Cathedral training images.
After downloading and running "create_MD_train_val.py" to create trainset, I got error, 

FileNotFoundError: [Errno 2] No such file or directory: '/phoenix/S6/zl548/MegaDpeth_code//final_list/train_val_list/landscape/imgs_MD.p'

So, please let me know the name of the directory for Florence Cathedral folders in MegaDepth files
or give some recommendations for dealing this issue. ^^

**Comment by monniert** [comment]
Hi, sure the directory name corresponding to Florence’s cathedral should be 0032. The list and description of the landmarks are also available at http://landmark.cs.cornell.edu/Landmarks3/
